#!/bin/bash

HERE=$(python -c 'import sys, os; print(os.path.dirname(os.path.realpath(sys.argv[1])))' "${BASH_SOURCE[0]}")
PNP="$HOME/.pride-and-prejudice.txt"

test -f "$PNP" || cp "$HERE/pride-and-prejudice.txt" "$PNP"

PNP_SHA256="$(shasum -a 256 < "$PNP" | sed 's/ .*//')"
if [ "$PNP_SHA256" != '53c585e8d3df3fba73e2dcbfb51d1ca2aab0287384ec2a052435950907d9f6b8' ]; then
    echo "Pride and Prejudice has unexpected checksum (expected 53c585e8..., got $PNP_SHA256)" >&2
    return 1
fi

read -s -p "Seed: " SEED
SEED="$SEED $*"
echo
export SEED
env | sed -n -e 's/^SEED=//p' | tr -d '\n' | shasum -a 256 | cut -c 1-64 | python "$HERE/hex-to-words" "$PNP"
