#!/bin/bash

HERE=$(python -c 'import sys, os; print(os.path.dirname(os.path.realpath(sys.argv[1])))' "${BASH_SOURCE[0]}")
SALT=$1
shift

read -s -p "Seed: " SEED
SEED="$SEED $SALT"
echo
export SEED
env | sed -n -e 's/^SEED=//p' | tr -d '\n' | shasum -a 256 | cut -c 1-64 | python "$HERE/hex-to-gobbledygook" "$@"
